apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: serverteam-pxe
    name: serverteam-pxe
    namespace: default
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: serverteam-pxe
      spec:
        containers:
        - image: docker.io/npflan/serverteam-pxe:latest
          imagePullPolicy: Always
          name: serverteam-pxe
          
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: serverteam-pxe
    name: serverteam-pxe
    namespace: default
  spec:
    clusterIP: None
    ports:
    - name: pxe-udp
      port: 69
      protocol: UDP
      targetPort: 69
    - name: pxe-http
      port: 8080
      protocol: UDP
      targetPort: 80
    selector:
      app: serverteam-pxe
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
